// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekubppuvemqbseiybgrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrdWJwcHV2ZW1xYnNlaXliZ3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5Mzk0MDAsImV4cCI6MjA2MTUxNTQwMH0.Wk77LSmAZdRs_eyJcSYWoKStlj5n5X9bW9NBKytpuyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);